# Generated by Django 4.2.3 on 2023-07-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('trade_date', models.DateField()),
                ('trade_type', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('split_ratio', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
